version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region "$AWS_DEFAULT_REGION" | docker login --username AWS --password-stdin "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"
      - NGINX_REPOSITORY_URL="$NGINX_REPO_URL"
      - PYTHON_REPOSITORY_URL="$PYTHON_REPO_URL"
      - COMMIT_HASH=$(echo "$CODEBUILD_RESOLVED_SOURCE_VERSION" | cut -c1-7)
      - IMAGE_TAG="${COMMIT_HASH:-latest}"
  build:
    commands:
      - echo Build started on `date`
      - echo Building nginx image...
      - docker build ./fastapi/web/Dockerfile -t $NGINX_REPOSITORY_URL:latest
      - docker tag $NGINX_REPOSITORY_URL:latest $NGINX_REPOSITORY_URL:$IMAGE_TAG
      - echo Building python image...
      - docker build ./fastapi/app/Dockerfile -t $PYTHON_REPOSITORY_URL:latest
      - docker tag $PYTHON_REPOSITORY_URL:latest $PYTHON_IMAGE_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Pushing nginx image...
      - docker push "$NGINX_REPOSITORY_URL:latest"
      - docker push "$NGINX_REPOSITORY_URL:$IMAGE_TAG"
      - echo Pushing python image...
      - docker push "$PYTHON_REPOSITORY_URL:latest"
      - docker push "$PYTHON_IMAGE_URI:$IMAGE_TAG"
      - echo Substituting image URIs into taskdef.json...
      - sed -i -e "s#<PROJECT>#$PROJECT#g" terraform/scripts/taskdef.json
      - sed -i -e "s#<ENV>#$ENV#g" terraform/scripts/taskdef.json
      - sed -i -e "s#<EXECUTION_ROLE_ARN>#$EXECUTION_ROLE_ARN#g" terraform/scripts/taskdef.json
      - sed -i -e "s#<TASK_ROLE_ARN>#$TASK_ROLE_ARN#g" terraform/scripts/taskdef.json
      - sed -i -e "s#<NGINX_REPOSITORY_URL>#$NGINX_REPOSITORY_URL#g" terraform/scripts/taskdef.json
      - sed -i -e "s#<NGINX_CONTAINER_PORT>#$NGINX_CONTAINER_PORT#g" terraform/scripts/taskdef.json
      - sed -i -e "s#<PYTHON_REPOSITORY_URL>#$PYTHON_REPOSITORY_URL#g" terraform/scripts/taskdef.json
      - sed -i -e "s#<PYTHON_CONTAINER_PORT>#$PYTHON_CONTAINER_PORT#g" terraform/scripts/taskdef.json
      - sed -i -e "s#<REGION>#$REGION#g" terraform/scripts/taskdef.json
      - cp terraform/scripts/taskdef.json ./
      - echo Finished Rewriting task definitions file
      - echo Rewriting appspec file...
      - sed -i -e "s#<PROJECT>#$PROJECT#g" terraform/scripts/appspec.yaml
      - sed -i -e "s#<ENV>#$ENV#g" terraform/scripts/appspec.yaml
      - echo Finished Rewriting appspec file
      - cp terraform/scripts/appspec.yaml ./

artifacts:
  files:
    - appspec.yaml
    - taskdef.json
